[general]
import = [
"themes/tokyo-fork.toml"
]

[window]
opacity = 0.5
padding = { x = 0, y = 0}
dynamic_padding = false
decorations = "None"


[font]
normal = { family = "Iosevka Nerd Font", style="Medium"}
bold = { family = "Iosevka Nerd Font", style="ExtraBold"}
italic = { family =  "Iosevka Nerd Font", style="Medium Italic"}
bold_italic = { family =  "Iosevka Nerd Font", style="ExtraBold Italic"}
size = 11

# normal = { family = "RecMonoLinear Nerd Font", style="Regular"}
# bold = { family =  "RecMonoLinear Nerd Font Propo", style="Bold"}
# italic = { family =  "RecMonoDuotone Nerd Font", style="Italic"}
# bold_italic = { family =  "RecMonoDuotone Nerd Font", style="Bold"}



